# Generated by Django 3.2.7 on 2021-11-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_balance_expense_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='repetition_interval',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Not Applicable'), (2, 'DAYS'), (3, 'WEEKS'), (4, 'MONTHS'), (5, 'YEARS')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='repetition_time',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='income',
            name='repetition_interval',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Not Applicable'), (2, 'DAYS'), (3, 'WEEKS'), (4, 'MONTHS'), (5, 'YEARS')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='repetition_time',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='balance',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CUR'), (2, 'SAVINGS')]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'SALARY'), (2, 'BONUS'), (3, 'LIGHT'), (4, 'WATER'), (5, 'MAINTENANCE'), (6, 'TAX'), (7, 'OTHERS')]),
        ),
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CONSULTATION'), (2, 'DONATIONS')]),
        ),
    ]
